name: ppp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  audio_service: ^0.18.9
  flex_color_scheme: ^6.1.1
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.1
  google_fonts: ^3.0.1
  just_audio: ^0.9.32
  rive: ^0.10.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Nabla
      fonts:
        - asset: assets/fonts/Nabla-Regular.ttf
    - family: Rubik Maze
      fonts:
        - asset: assets/fonts/RubikMaze-Regular.ttf
  shaders:
    - shaders/sierpinski_carpet.frag
    - shaders/hello_world.frag
    - shaders/water.frag
    - shaders/mandelbrot_set.frag


