import 'dart:convert';
import 'dart:typed_data';
import 'dart:ui';

import 'package:umbra_flutter/umbra_flutter.dart';

/// {@template hello_world_shader}
/// A Flutter Widget for the `hello_world_shader` shader.
/// {@endtemplate}
class HelloWorldShader extends UmbraWidget {
  /// {@macro hello_world_shader}
  const HelloWorldShader({
    super.key,
    super.blendMode = BlendMode.src,
    super.child,
    super.errorBuilder,
    super.compilingBuilder,
    required double uTime,
    required Vector2 uMouse,
  })  : _uTime = uTime,
        _uMouse = uMouse,
        super();

  static Future<FragmentProgram>? _cachedProgram;

  final double _uTime;

  final Vector2 _uMouse;

  @override
  List<double> getFloatUniforms() {
    return [
      _uTime,
      _uMouse.x,
      _uMouse.y,
    ];
  }

  @override
  List<ImageShader> getSamplerUniforms() {
    return [];
  }

  @override
  Future<FragmentProgram> program() {
    return _cachedProgram ??
        FragmentProgram.compile(
          spirv: Uint8List.fromList(base64Decode(_spirv)).buffer,
        );
  }
}

const _spirv =
    'AwIjBwAAAQAKAA0AMgAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ABwAEAAAABAAAAG1haW4AAAAAJAAAACsAAAAQAAMABAAAAAgAAAADAAMAAQAAAEABAAAEAAoAR0xfR09PR0xFX2NwcF9zdHlsZV9saW5lX2RpcmVjdGl2ZQAABAAIAEdMX0dPT0dMRV9pbmNsdWRlX2RpcmVjdGl2ZQAFAAQABAAAAG1haW4AAAAABQAHAA0AAABmcmFnbWVudCh2ZjI7dmYyOwAAAAUAAwALAAAAdXYAAAUABQAMAAAAZnJhZ0Nvb3JkAAAABQAEABAAAAB1X3RpbWUAAAUABAAUAAAAdV9tb3VzZQAFAAMAIgAAAHV2AAAFAAYAJAAAAGdsX0ZyYWdDb29yZAAAAAAFAAUAJwAAAHJlc29sdXRpb24AAAUABAArAAAAX0NPTE9SXwAFAAQALAAAAHBhcmFtAAAABQAEAC4AAABwYXJhbQAAAEcAAwANAAAAAAAAAEcAAwALAAAAAAAAAEcAAwAMAAAAAAAAAEcAAwAQAAAAAAAAAEcABAAQAAAAHgAAAAAAAABHAAMAEQAAAAAAAABHAAMAEgAAAAAAAABHAAMAFAAAAAAAAABHAAQAFAAAAB4AAAABAAAARwADABgAAAAAAAAARwADABkAAAAAAAAARwADABwAAAAAAAAARwADAB0AAAAAAAAARwADAB8AAAAAAAAARwADACIAAAAAAAAARwAEACQAAAALAAAADwAAAEcAAwAnAAAAAAAAAEcABAAnAAAAHgAAAAIAAABHAAMAKAAAAAAAAABHAAMAKwAAAAAAAABHAAQAKwAAAB4AAAAAAAAARwADACwAAAAAAAAARwADAC0AAAAAAAAARwADAC4AAAAAAAAARwADADEAAAAAAAAAEwACAAIAAAAhAAMAAwAAAAIAAAAWAAMABgAAACAAAAAXAAQABwAAAAYAAAACAAAAIAAEAAgAAAAHAAAABwAAABcABAAJAAAABgAAAAQAAAAhAAUACgAAAAkAAAAIAAAACAAAACAABAAPAAAAAAAAAAYAAAA7AAQADwAAABAAAAAAAAAAIAAEABMAAAAAAAAABwAAADsABAATAAAAFAAAAAAAAAAVAAQAFQAAACAAAAAAAAAAKwAEABUAAAAWAAAAAAAAACsABAAVAAAAGgAAAAEAAAArAAQABgAAAB4AAAAAAIA/IAAEACMAAAABAAAACQAAADsABAAjAAAAJAAAAAEAAAA7AAQAEwAAACcAAAAAAAAAIAAEACoAAAADAAAACQAAADsABAAqAAAAKwAAAAMAAAA2AAUAAgAAAAQAAAAAAAAAAwAAAPgAAgAFAAAAOwAEAAgAAAAiAAAABwAAADsABAAIAAAALAAAAAcAAAA7AAQACAAAAC4AAAAHAAAAPQAEAAkAAAAlAAAAJAAAAE8ABwAHAAAAJgAAACUAAAAlAAAAAAAAAAEAAAA9AAQABwAAACgAAAAnAAAAiAAFAAcAAAApAAAAJgAAACgAAAA+AAMAIgAAACkAAAA9AAQABwAAAC0AAAAiAAAAPgADACwAAAAtAAAAPQAEAAkAAAAvAAAAJAAAAE8ABwAHAAAAMAAAAC8AAAAvAAAAAAAAAAEAAAA+AAMALgAAADAAAAA5AAYACQAAADEAAAANAAAALAAAAC4AAAA+AAMAKwAAADEAAAD9AAEAOAABADYABQAJAAAADQAAAAAAAAAKAAAANwADAAgAAAALAAAANwADAAgAAAAMAAAA+AACAA4AAAA9AAQABgAAABEAAAAQAAAADAAGAAYAAAASAAAAAQAAAA0AAAARAAAAQQAFAA8AAAAXAAAAFAAAABYAAAA9AAQABgAAABgAAAAXAAAADAAGAAYAAAAZAAAAAQAAAA0AAAAYAAAAQQAFAA8AAAAbAAAAFAAAABoAAAA9AAQABgAAABwAAAAbAAAADAAGAAYAAAAdAAAAAQAAAA0AAAAcAAAAUAAHAAkAAAAfAAAAEgAAABkAAAAdAAAAHgAAAP4AAgAfAAAAOAABAA==';
